"""Pack everything in ../assets into ../js/assets.js as data URIs.

Why: browsers refuse to feed local image files into WebGL when index.html is opened
straight from disk (file://). Embedding the images as data URIs sidesteps that, so the
app works with a double-click and no web server.

Run after changing anything in assets/:   python tools/pack_assets.py
"""
import base64
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
A = os.path.join(ROOT, 'assets')


def uri(path):
    ext = os.path.splitext(path)[1].lower()
    mime = {'.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png', '.webp': 'image/webp'}[ext]
    with open(path, 'rb') as f:
        return f'data:{mime};base64,' + base64.b64encode(f.read()).decode()


meta = json.load(open(os.path.join(A, 'meta.json')))
angles = []
for i, ang in enumerate(meta['angles']):
    d = os.path.join(A, f'angle{i}')
    angles.append({
        'medians': ang['medians'],
        'base': uri(os.path.join(d, 'base.jpg')),
        'shade': uri(os.path.join(d, 'shade.png')),
        'masks': [uri(os.path.join(d, f)) for f in sorted(os.listdir(d)) if f.startswith('mask')],
    })
patterns = []
for p in json.load(open(os.path.join(A, 'patterns', 'patterns.json'))):
    fn = next(f for f in os.listdir(os.path.join(A, 'patterns')) if os.path.splitext(f)[0] == p['id']
              and not f.endswith('.json'))
    patterns.append({**p, 'src': uri(os.path.join(A, 'patterns', fn))})

out = {'items': meta['items'], 'tint': meta.get('tint', [1, 1, 1]), 'width': meta['width'], 'height': meta['height'],
       'angles': angles, 'patterns': patterns}
with open(os.path.join(ROOT, 'js', 'assets.js'), 'w') as f:
    f.write('// Generated by tools/pack_assets.py - do not edit by hand.\n')
    f.write('window.LOADOUT_ASSETS = ' + json.dumps(out) + ';\n')
print('wrote js/assets.js', round(os.path.getsize(os.path.join(ROOT, 'js', 'assets.js')) / 1e6, 2), 'MB')
